# Generated by Django 4.1.7 on 2023-03-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_remove_film_rezyser_remove_film_tytul_film_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='name',
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='film',
            name='plakat',
            field=models.ImageField(blank=True, null=True, upload_to='plakaty'),
        ),
        migrations.AddField(
            model_name='film',
            name='premiere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(default='', max_length=30),
        ),
    ]
